### ISSUE TITLE
thows a missing argument exception when running on symfony 2.3

### ISSUE THREAD

**Issue by longnd** [armetiz/LeezyPheanstalkBundle#60]
I'm using your bundle (v3.1) on a symfony 2.3 project. It throws a "Missing argument" exception on **PheanstalkLogListener/ onCommand()** function. (screenshot 1 bellow)
The missing exception is $eventname. if I change the function to remove that parameter and in the code, get the event name by: `$event->getName()`, it works (screenshot 2)

**_Screenshot 1:_**
![missing argument](https://cloud.githubusercontent.com/assets/1896814/13243672/4cb07930-da33-11e5-8b91-c3cefdfa68a5.JPG)

**_Screenshot 2:_**
![updated function](https://cloud.githubusercontent.com/assets/1896814/13243691/72efcfce-da33-11e5-87e1-5353789c416f.JPG)

**Comment by armetiz** [comment]
Hi @longnd 

I'm sorry, but the 3.x version of LeezyPheanstalkBundle is not Symfony 2.3 compliant due to a BC coming from symfony/event-dispatcher v2.4.

If you need this version of PheanstalkBundle, please upgrade your Symfony project to the 2.5.

PS : I made dependencies updates within 3.1.1 & 3.0.1

Regards.
Thomas.

**Comment by longnd** [comment]
Thanks @armetiz for the reply. 
Since I can not upgrade my Symfony to a newer version, I guess the only solution is to use the 2.5 version of the bundle.
Are there any drawbacks of this version?

btw, I think it's better if you state the Requirements (like the minimum Symfony version, etc) in the Document.

Anw, thank you for this great bundle.

**Comment by armetiz** [comment]
The main difference is about PSR-3
